### ISSUE TITLE
failed to load source for dependency `glium`

### ISSUE THREAD

**Issue by happysmash27** [yshui/picom-xrdesktop-companion#1]
When running cargo build --release directly from Git, the error occurs: 

```
 % cargo build --release
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `glium`

Caused by:
  Unable to update /home/happysmash27/Gits/picom-xrdesktop-companion/glium

Caused by:
  failed to read `/home/happysmash27/Gits/picom-xrdesktop-companion/glium/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Even after running `git submodule init` and `git submodule update --init --recursive`, it does not pull in glium, but only gir-files.

**Comment by yshui** [comment]
Hey, thanks for trying this. You are clearly the first person ever beside me to use this :smile:. I pushed a fix, can you try it?

**Comment by happysmash27** [comment]
Now this issue seems to be fixed! Still get compile errors but they are separate. 

Strangely, they seem to be different from the errors I was getting before with my own fix – maybe Rust is compiling all the packages for my user rather than for this project specifically? 

Original errors were: 

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> app/src/main.rs:1:1
  |
1 | / #![feature(
2 | |     never_type,
3 | |     backtrace,
4 | |     box_into_inner,
5 | |     downcast_unchecked,
6 | |     map_try_insert
7 | | )]
  | |__^

error[E0599]: no method named `downcast_unchecked` found for struct `std::boxed::Box<dyn std::any::Any + std::marker::Send>` in the current scope
  --> app/src/utils.rs:89:40
   |
89 |             self.call_inner(f)?.await?.downcast_unchecked::<R>()
   |                                        ^^^^^^^^^^^^^^^^^^ method not found in `std::boxed::Box<dyn std::any::Any + std::marker::Send>`

error[E0599]: no method named `downcast_unchecked` found for struct `std::boxed::Box<dyn std::any::Any + std::marker::Send>` in the current scope
   --> app/src/utils.rs:100:18
    |
100 |                 .downcast_unchecked::<R>()
    |                  ^^^^^^^^^^^^^^^^^^ method not found in `std::boxed::Box<dyn std::any::Any + std::marker::Send>`

Some errors have detailed explanations: E0554, E0599.
For more information about an error, try `rustc --explain E0554`.
error: could not compile `app` due to 3 previous errors
```

For which I am updating Rust, which will hopefully fix them. 

Newer compile features approximately 461 errors starting with: 
`error: `CStr::from_bytes_with_nul_unchecked` is not yet stable as a const fn`
in ~/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.37.0+1.3.209/src/vk/extensions.rs

That would be a separate issue though, in the latter issue's case probably not even with this package, and might be fixed on its own by updating Rust, so I think this issue can be considered closed. Thank you!

**Comment by yshui** [comment]
@happysmash27 you need to install rust from the nightly channel.

**Comment by happysmash27** [comment]
Was hoping to avoid nightly because running the unstable version could potentially be annoying in regards to versioning. So, I decided to update to the newest normal version instead, in hopes that the feature had been around long enough that it was no longer in nightly. 

Unfortunately the `#![feature]` feature is not enabled even on the newest version though, so I guess, after finally compiling the latest version, I need to spend yet another hour or so compiling it again! 

Though, now that I check, it turns out I don't need to be running the most up-to-date version to get that at all; I can just enable the `nightly` USE flag in Gentoo which will enable it regardless of how stable the version actually is. So, I can continue using the same semi-stable version as before, at least.

**Comment by happysmash27** [comment]
Compilation works now with `nightly` use flag! Or, actually yesterday, but I'm just getting to commenting on it now.
